### ISSUE TITLE
MultiValueDictKeyError at /api/gitrepo_export/update_book_repo/ 'repo_name'

### ISSUE THREAD

**Issue by almereyda** [fiduswriter/fiduswriter-github-export#5]
This has been derived with a custom Docker build, an officially unsupported version, but might still help gather runtime evidence.

The error appeared when wanting to print a book configured to GitLab, with books previously tied to GitHub present, while the latter `socialauth` provider had already been disabled again.

<details>

<summary>Error sent to the `ADMINS`</summary>

```py
Internal Server Error: /api/gitrepo_export/update_book_repo/

MultiValueDictKeyError at /api/gitrepo_export/update_book_repo/
'repo_name'

Request Method: POST
Request URL: https://writer.allmende.io/api/gitrepo_export/update_book_repo/
Django Version: 3.2.5
Python Executable: /usr/bin/python3
Python Version: 3.8.10
Python Path: ['/fiduswriter', '/usr/local/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.8/dist-packages/fiduswriter']
Server time: Thu, 10 Feb 2022 00:30:15 +0000
Installed Applications:
['npm_mjs',
 'base',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.flatpages',
 'django_js_error_hook',
 'loginas',
 'fixturemedia',
 'browser_check',
 'menu',
 'document',
 'bibliography',
 'usermedia',
 'user',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'avatar',
 'feedback',
 'style',
 'allauth.socialaccount.providers.gitlab',
 'book',
 'citation_api_import',
 'languagetool',
 'ojs',
 'phplist',
 'gitrepo_export']
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware']


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)

During handling of the above exception ('repo_name'), another exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fiduswriter/base/decorators.py", line 19, in wrap
    return f(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fiduswriter/gitrepo_export/views.py", line 59, in update_book_repo
    repo_name=request.POST["repo_name"],
  File "/usr/local/lib/python3.8/dist-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)

Exception Type: MultiValueDictKeyError at /api/gitrepo_export/update_book_repo/
Exception Value: 'repo_name'
Request information:
USER: yala

GET: No GET data

POST:
csrfmiddlewaretoken = 'HDTOrJsnynp7ybOrOqvbZkSkOx2oV9CvfiUAVt0cuWzOo6WrYCojNvspS5NIwamu'
book_id = '1'
repo_type = ''
repo_id = '0'

FILES: No FILES data

COOKIES:
rl_anonymous_id = 'RudderEncrypt%3AU2FsdGVkX188iwD7SBM4EkHb1M3AWULxvUw5cbb3Pkg%2B2vYSDjruyqLZ%2BYRasEqIF7mpgynSo6A1YeqKpWE2aA%3D%3D'
rl_user_id = 'RudderEncrypt%3AU2FsdGVkX19LmIr0Z7hng7wURwZxF2JaigNArPFpKs3AFMMoPB3pVzCePxvJpQtV'
rl_group_id = 'RudderEncrypt%3AU2FsdGVkX19kacFxWNZmzIF55JvHQmt%2BPY5XmrH57ig%3D'
rl_trait = 'RudderEncrypt%3AU2FsdGVkX189AdaKv75cMjFT%2BWlGZnRY3pt245zzpdU%3D'
rl_group_trait = 'RudderEncrypt%3AU2FsdGVkX1%2BcwL9ISe5pE043nGZLnPOq1NSaxWAxxkM%3D'
rl_page_init_referrer = 'RudderEncrypt%3AU2FsdGVkX1%2By9xrNsEefED2eQHouijltsEfqaPjUxeY%3D'
rl_page_init_referring_domain = 'RudderEncrypt%3AU2FsdGVkX19twVIfrTBUM2LsltAInjs6PUOjxW3RMjs%3D'
logged_out_marketing_header_id = 'eyJfcmFpbHMiOnsibWVzc2FnZSI6IklqWXpZMkUwTVdVMExURm1ORE10TkRNME1TMDRNak5pTFRCbE56RmlPR0kyTkRSbE5pST0iLCJleHAiOm51bGwsInB1ciI6ImNvb2tpZS5sb2dnZWRfb3V0X21hcmtldGluZ19oZWFkZXJfaWQifX0%3D--83b8fb09efd70fc5a65d70a5c54be447ac5a6d99'
csrftoken = 'HDTOrJsnynp7ybOrOqvbZkSkOx2oV9CvfiUAVt0cuWzOo6WrYCojNvspS5NIwamu'
sessionid = '45g3ymlyg0cy1e20hrwqsnp4fjqmxh8p'

META:
CONTENT_LENGTH = '585'
CONTENT_TYPE = 'multipart/form-data; boundary=---------------------------5663315523319292143770686778'
CSRF_COOKIE = 'HDTOrJsnynp7ybOrOqvbZkSkOx2oV9CvfiUAVt0cuWzOo6WrYCojNvspS5NIwamu'
HTTP_ACCEPT = 'application/json'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE = 'de,en-US;q=0.7,en;q=0.3'
HTTP_COOKIE = 'rl_anonymous_id=RudderEncrypt%3AU2FsdGVkX188iwD7SBM4EkHb1M3AWULxvUw5cbb3Pkg%2B2vYSDjruyqLZ%2BYRasEqIF7mpgynSo6A1YeqKpWE2aA%3D%3D; rl_user_id=RudderEncrypt%3AU2FsdGVkX19LmIr0Z7hng7wURwZxF2JaigNArPFpKs3AFMMoPB3pVzCePxvJpQtV; rl_group_id=RudderEncrypt%3AU2FsdGVkX19kacFxWNZmzIF55JvHQmt%2BPY5XmrH57ig%3D; rl_trait=RudderEncrypt%3AU2FsdGVkX189AdaKv75cMjFT%2BWlGZnRY3pt245zzpdU%3D; rl_group_trait=RudderEncrypt%3AU2FsdGVkX1%2BcwL9ISe5pE043nGZLnPOq1NSaxWAxxkM%3D; rl_page_init_referrer=RudderEncrypt%3AU2FsdGVkX1%2By9xrNsEefED2eQHouijltsEfqaPjUxeY%3D; rl_page_init_referring_domain=RudderEncrypt%3AU2FsdGVkX19twVIfrTBUM2LsltAInjs6PUOjxW3RMjs%3D; logged_out_marketing_header_id=eyJfcmFpbHMiOnsibWVzc2FnZSI6IklqWXpZMkUwTVdVMExURm1ORE10TkRNME1TMDRNak5pTFRCbE56RmlPR0kyTkRSbE5pST0iLCJleHAiOm51bGwsInB1ciI6ImNvb2tpZS5sb2dnZWRfb3V0X21hcmtldGluZ19oZWFkZXJfaWQifX0%3D--83b8fb09efd70fc5a65d70a5c54be447ac5a6d99; csrftoken=HDTOrJsnynp7ybOrOqvbZkSkOx2oV9CvfiUAVt0cuWzOo6WrYCojNvspS5NIwamu; sessionid=45g3ymlyg0cy1e20hrwqsnp4fjqmxh8p'
HTTP_DNT = '1'
HTTP_HOST = 'writer.allmende.io'
HTTP_ORIGIN = 'https://writer.allmende.io/'
HTTP_REFERER = 'https://writer.allmende.io/books/'
HTTP_SEC_FETCH_DEST = 'empty'
HTTP_SEC_FETCH_MODE = 'cors'
HTTP_SEC_FETCH_SITE = 'same-origin'
HTTP_SEC_GPC = '1'
HTTP_TE = 'trailers'
HTTP_USER_AGENT = 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0'
HTTP_X_CSRFTOKEN = '********************'
HTTP_X_FORWARDED_FOR = '78.94.219.59, 172.19.0.2'
HTTP_X_FORWARDED_HOST = 'writer.allmende.io'
HTTP_X_FORWARDED_PORT = '443'
HTTP_X_FORWARDED_PROTO = 'https'
HTTP_X_FORWARDED_SERVER = 'efd9aa5bde2d'
HTTP_X_REAL_IP = '78.94.219.59'
HTTP_X_REQUESTED_WITH = 'XMLHttpRequest'
PATH_INFO = '/api/gitrepo_export/update_book_repo/'
QUERY_STRING = ''
REMOTE_ADDR = '78.94.219.59'
REQUEST_METHOD = 'POST'
SCRIPT_NAME = ''
SERVER_NAME = 'writer.allmende.io'
SERVER_PORT = '443'
SERVER_PROTOCOL = 'HTTP/1.1'
wsgi.errors = <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
wsgi.input = <_io.BytesIO object at 0x7f920edba180>
wsgi.multiprocess = True
wsgi.multithread = False
wsgi.run_once = False
wsgi.url_scheme = 'https'
wsgi.version = '(1, 0)'
```

</details>

[🔗 `settings.py`](https://lab.allmende.io/-/snippets/421)

**Comment by almereyda** [comment]
```py
Exception Type: MultiValueDictKeyError at /api/gitrepo_export/update_book_repo/
Exception Value: 'repo_name'
Request information:
USER: yala

GET: No GET data

POST:
csrfmiddlewaretoken = 'HDTOrJsnynp7ybOrOqvbZkSkOx2oV9CvfiUAVt0cuWzOo6WrYCojNvspS5NIwamu'
book_id = '1'
repo_type = ''
repo_id = '0'

FILES: No FILES data
```

Is this hinting us at a client fallacy, rather than a server problem?

**Comment by johanneswilm** [comment]
I assume this has been resolved since as a lot of the code has been rewritten. Please reopen if it persists.
